// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:investor_hub/features/auth/data/models/session_model.dart';
import 'package:investor_hub/features/auth/data/models/user_model.dart';
import 'package:investor_hub/features/deals/data/models/deal_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DealModelAdapter());
    registerAdapter(SessionModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DealModelAdapter());
    registerAdapter(SessionModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
